Instruct creation of the `imports` directory and clarify its purpose.
meteor/tutorials pull request #117
Opened 2017-03-16 12:49 UTC by abernix

Previously, we failed to explicitly instruct the developer to create the
`imports` directory on the Blaze, Angular and React tutorials.  While
the path was implied in the top-right corner of the code-snippet boxes,
we should be more clear about this and we can also take the opportunity
to emphasize the importance and significance of the directory.

We do mention a place to find more information about how imports work,
but not until a later step.  This information was also excluded from the
Angular tutorial, so this also adds the same blurb for that.

Follows-up on meteor/tutorials#86.

This also fixes the phrase "entry point" to be consistently represented as two distinct words.  I'm not sure if "entry point" should be hyphenated or not and have gone with the hyphenated approach as I believe it's most appropriate, but "entrypoint" is definitely not a word.  Happy to remove the hyphen but I don't know if there's a right answer.

(Also, a couple other minor grammatical changes.)

/cc @lazaridis-com

2017-03-16 15:07 UTC, hwillson requested changes
Looks great @abernix! Just a few small grammar issues / typos.

2017-03-16 15:07 UTC, hwillson commented on content/angular/step02.md
> +Now we need to create a new directory called `imports`, a specially-named directory which will behave different than other directories in the project.  Files outside the `imports` directory will be l
Small grammar issue - "which will behave different" should be "which will behave differently".

2017-03-16 15:07 UTC, hwillson commented on content/angular/step02.md
> +After creating the `imports` directory, we will create new two new files inside it.
"new" is repeated twice.

2017-03-16 15:07 UTC, hwillson commented on content/react/step02.md
> +Now we need to create a new directory called `imports`, a specially-named directory which will behave different than other directories in the project.  Files outside the `imports` directory will be l
Same "differently" comment as above.

2017-03-16 15:07 UTC, hwillson commented on content/react/step02.md
> +After creating the `imports` directory, we will create new two new files inside it:
Same duplicate "new" issue.

2017-03-16 16:33 UTC, abernix commented
Thanks, @hwillson.  Should be fixed now.  I had "differently" before but I truly wasn't sure what I thought of it. 

Feel free to "Squash and merge" if these look fixed to you now. :smile:

2017-03-20 11:42 UTC, hwillson approved these changes

2017-03-20 11:43 UTC, merged

2017-03-20 11:43 UTC, hwillson commented
Done - thanks @abernix!